### ISSUE TITLE
Adapt definedName when use tables dataSet

### ISSUE THREAD

**Issue by jdugh** [optilude/xlsx-template#122]
Hy @kant2002,

I have a Excel sheet with pagebreak layout.
If I add a table dataSet in the page 1, the page break don't moved.
I whant to move my pageBreak as far as tables substitution.
I have make this change : 
[pushdown BageBreak with tables substitution](https://github.com/jdugh/xlsx-template/commit/a563a1bffb7acba54caaaf809c5536368f4fbfdd)

But some of test has broken.
What do you think about that ?
May I can add an option (like the images option) for active or not the pushdown on pageBreak. Or there is an another way for make that ?

Thank's

**Comment by kant2002** [comment]
Yes. I want to be as much compatible as possible. I.e. goal 100% compatibility. So please go with new option. Please create new test to validate that option. That way we will know that we care about your case.

**Comment by jdugh** [comment]
Ho yes ! I had not thought of with an option, all other tests would be good. Ok so good ! wait for the next PR

**Comment by jdugh** [comment]
[Fonctionnality propose in this PR](https://github.com/optilude/xlsx-template/pull/124)
