### ISSUE TITLE
Image is added as a string

### ISSUE THREAD

**Issue by ravi-poonia** [optilude/xlsx-template#134]
I'm trying to add to a cell, I have used the absolute path, base64...it's not working. I even used Base64 from the tests just to make sure. 

Whatever I use, it's inserted as a string instead of an image. Am I missing something?

**Comment by ravi-poonia** [comment]
When I ran the tests in my local, it worked perfectly

But when I tried the image  insert test with my nodejs app, got string instead of an image

**Comment by ravi-poonia** [comment]
After some more testing, it seems the issue is due to the package versions...either image-size or jszip, once I manually added the lib file and added the packages with the same version specified in the repo, it started working. I'll see if I make the repo work with the latest version of the dependencies. I'm closing it for now. Thx

**Comment by RactivussDevs** [comment]
What version of xlsx-template are u using? And do I need to install image-size and jszip packages? What does this packages work for?

**Comment by ravi-poonia** [comment]
These 2 are dependencies of the library. They are probably used to render the image in a cell. Other stuff will still work but the image insert was not working.

**Comment by benoitlavorata** [comment]
In case someone is not clear about ravi-poonia ' answer, here are steps to make it work until the package on npm is updated:
- download the zip of xlsx-template somwhere at the root of your app folder, from github, download zip
- add these dependencies to your package.json file 
```json
    "elementtree": "0.1.6",
    "image-size": "0.3.5",
    "jszip": "2.6.1"
    ```
 - run ```npm install```
 - make sure you call xlsx-template using your local path, something like ```require('./xlsx-template/lib/index)```
 
 Then you can easily add pictures in your excel.
