### ISSUE TITLE
How to download file?

### ISSUE THREAD

**Issue by jaider2523** [optilude/xlsx-template#14]
Hi, 

How to download file from server.....and.....how to retrieve in the frontend....

```
  // Get binary data backend
      var data = template.generate();
      res.setHeader('Content-Type', 'application/vnd.openxmlformats');
        res.setHeader("Content-Disposition", "attachment; filename=" + "Report.xlsx");
        res.end(data, 'binary');
```

//Frontend...
Get ajax?

**Comment by mrothberg** [comment]
I'm not sure if this is the optimal solution, as it seems a little hacky, but it works and its what I'm doing in my application.
In the backend, I use res.download() to send back the file that the template generated, after saving it to disk.
In the frontend (I'm using angular.js), I create a blob to hold the binary content that the backend returns. I then create a link to the blob (fileURL) object, and create an a element whose href is the link to the blob.

```javascript
// backend (/api/userXLSXTemplate)

// ...

var output = template.generate();

var filePath = __dirname + '/fileName.xlsx'

fs.writeFile(filePath, output, 'binary', function(err){
    if(err) console.log(err);
    res.download(filePath);
});

//frontend js

$scope.downloadTemplate = function() {

  $http({
      url: '/api/useXLSXTemplate',
      method: "POST",
      headers: {
         'Content-type': 'application/json'
      },
      responseType: 'arraybuffer'
  }).success(function (data, status, headers, config) {
      var blob = new Blob([data], {type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"});
      var fileName = headers('Content-Disposition').split('"')[1];
      var fileURL = URL.createObjectURL(blob);
      var a = document.createElement('a');
      a.href = fileURL;
      a.target = '_blank';
      a.download = fileName;
      document.body.appendChild(a);
      a.click();
  }).error(function (data, status, headers, config) {
      //download failed
  });

};
```

**Comment by jaider2523** [comment]
Hi,

Thanks for your answer, but i don't want save the file on the disk after send to user, because is a spend unnecesary the space, It's my point of view. But your idea can work, i will to try. 

Thanks...

**Comment by jaider2523** [comment]
Hi,

The code ......with minor changes it worked. Thanks.

**Comment by mrothberg** [comment]
I know this is a late reply, but glad it worked!
