### ISSUE TITLE
Write to merged cells

### ISSUE THREAD

**Issue by Clan-Utility** [optilude/xlsx-template#17]
When I write tables, if ${table:people.name} is put in a merged cell, after calling template.substitute(), people.name is correctly placed in the merged cell only for the first row. For the following rows, people.name is placed in the 1st cell of the merged cell.

Any hint to solve that?

**Comment by woodenfish** [comment]
@Clan-Utility , I have this problem too. Do you have any solution?

**Comment by Clan-Utility** [comment]
Sadly no ...

**Comment by woodenfish** [comment]
@Clan-Utility I have fix this problem, just look at https://github.com/woodenfish/xlsx-template. And I will make a pull request to the master branch.

**Comment by Clan-Utility** [comment]
Tested. It works!
But for some cells, borders (top or bottom) are not set. No clue what caused the problem.

**Comment by woodenfish** [comment]
@Clan-Utility  Already fixed, Please pull and try again.

**Comment by Clan-Utility** [comment]
@woodenfish It's perfect!
