### ISSUE TITLE
 Is it possible to indent from the edge of the column so that the image is centered?

### ISSUE THREAD

**Issue by LuckyOne3** [optilude/xlsx-template#180]

**Comment by jdugh** [comment]
Hi @LuckyOne3 ,
Maybe this PR https://github.com/optilude/xlsx-template/pull/190 resolve your issue ?
Look here : https://github.com/optilude/xlsx-template?tab=readme-ov-file#images-in-cell

**Comment by LuckyOne3** [comment]
Yes, thanks



Отправлено из мобильной Почты Mail.ru


пятница, 19 апреля 2024 г. в 09:58 +03:00 от Jonathan Durand  ***@***.***>:
