### ISSUE TITLE
proplem : .join(self.prefix, '_rels', path.basename(workbookPath) + '.rels')).asText()).

### ISSUE THREAD

**Issue by forfuns** [optilude/xlsx-template#2]
my english no good,so pls try understand my word.

I learn a nodejs , build a project,I need a module export xlsx file, and I find xlsx-template ,
but something dont work and I dont work , and I cant fix,
so I find your contact , write a email , hope you can help me, thx!

the error msg:
```
.join(self.prefix, '_rels', path.basename(workbookPath) + '.rels')).asText()).
                                                                    ^
TypeError: Cannot call method 'asText' of null
    at module.exports.Workbook.loadTemplate (E:\WEB\model-chooese\node_modules\x
lsx-template\lib\index.js:50:131)
    at new module.exports.Workbook (E:\WEB\model-chooese\node_modules\xlsx-templ
ate\lib\index.js:27:18)
    at E:\WEB\model-chooese\app.js:56:20
    at fs.js:266:14
    at Object.oncomplete (fs.js:107:15)
```
and my code like this:
```
app.get('/api/save/:mark',function(req,res){
  var mark = req.params.mark;
  var file = __dirname+'\\public\\'+mark+'.xlsx';
  console.log(file);
  fs.readFile(file, function(err, data) {

    // Create a template
    console.log(data);
    var template = new XlsxTemplate(data);          //here is line 56
    console.log(template);

    // Replacements take place on first sheet
    var sheetNumber = 1;

    // Set up some placeholder values matching the placeholders in the template
    var values = {
      extractDate: new Date(),
      dates: [new Date("2013-06-01"),
            new Date("2013-06-02"),
            new Date("2013-06-03")
      ],
      people: [{
        name: "John Smith",
        age: 20
      }, {
        name: "Bob Johnson",
        age: 22
      }]
    };

    // Perform substitution
    template.substitute(sheetNumber, values);

    // Get binary data
    var data = template.generate();
    console.log(data);
    // ...

	// here , I wanna download this file , how can I do? what is  template.generate() return object?
  });


  //res.download(__dirname+'/public/'+mark+'.xls',mark+'.xls');
})

```

**Comment by ztripez** [comment]
I've got this aswell.

**Comment by limplash** [comment]
I got the same problem, but the module is working fine on linux.. if you guys are running on windows then please note the following changes that i made to make it work in windows.
Main reason  for the  error: The files in archive are indexed with linux style PATH naming, but the path module used to generate the path is creating windows style path (which it should do as we are on windows) so I have changed the following three lines in "node_modules\x
lsx-template\lib\index.js"

Line 50 : self.workbookRels = etree.parse(self.archive.file(path.join(self.prefix, '_rels', path.basename(workbookPath) + '.rels')).asText()).getroot();
TO : self.workbookRels = etree.parse(self.archive.file(path.join(self.prefix, '_rels', path.basename(workbookPath) + '.rels')).asText()).getroot();

Line 54 : self.sharedStringsPath = path.join(self.prefix, self.workbookRels.find("Relationship[@Type='" + SHARED_STRINGS_RELATIONSHIP + "']").attrib.Target);
TO : self.sharedStringsPath =self.prefix+'/'+self.workbookRels.find("Relationship[@Type='" + SHARED_STRINGS_RELATIONSHIP + "']").attrib.Target;

Then Add  the following line to Workbook.prototype.loadSheet functions just before the return 
info.filename = info.filename.replace(/\\/g,"/")

And you should have it running on windows 

Any one else with a better solution please share

**Comment by djholly123** [comment]
hi

tried this and it worked now able to use the module on windows ... many thanks!

**Comment by vp-vsean** [comment]
Thanks, limplash. I appreciate you work :)

**Comment by optilude** [comment]
I merged a PR that should have fixed this, try the latest code from github.
