### ISSUE TITLE
Dates corrupt file in Excel 2016 (v15.24) on Mac

### ISSUE THREAD

**Issue by wombat86** [optilude/xlsx-template#21]
I'm creating a table template with date column. After substitution is done and I open result in Excel I get the message saying that the file is corrupt and Excel proposes to try repairing this file.

When I investigated this issue for a while i noticed that Excel does not add "t" attribute for non-text cells (tested with numbers, dates, currency, percentage and general format) at all. I have a fix for this and am going to sign off a PR soon. Would be great if someone could test it in different version of Excel and also on Windows.

**Comment by bdunbar22** [comment]
Hi,

I am trying out xlsx-template to help in generating some excel documents and had the same corruption error on a Windows machine.

I tested these fixes on excel 2010 on Windows and they fixed the file corruption problem for dates and numbers. 

Thanks!
