### ISSUE TITLE
Can i write image in xlsx template?

### ISSUE THREAD

**Issue by pazalvin** [optilude/xlsx-template#23]
Can i write image in xlsx template?

**Comment by pentium100** [comment]
try this one: https://github.com/pentium100/xlsx-template
I forked, support image insert.

**Comment by pazalvin** [comment]
hi @pentium100 how did you write images? via base64? did you have a sample? so i can pattern it thanks in advance :-)

**Comment by marcus2vinicius** [comment]
@pazalvin 
`var photo = new Buffer(base64String, 'base64');`
in excel
`${image:photo}`
