### ISSUE TITLE
generate typings definition for typescript usage

### ISSUE THREAD

**Issue by phra** [optilude/xlsx-template#32]
hi.

it would be nice have also the typing definitions of this library in order to use it seamlessy within a typescript project.

**Comment by phra** [comment]
any update on this? it's a problem working with this library and have 'noImplicitAny' set to true in tsc config..

**Comment by kant2002** [comment]
@phra did you have your typings? Do you still need them? If so drop a line, so they could be implemented.

**Comment by phra** [comment]
i'm not actively using it anymore but for sure people can benefit from typings.

**Comment by kant2002** [comment]
It start appears in the repo, so it is a start. Thank for suggestion.
