### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by amenadiel** [optilude/xlsx-template#46]
@optilude if you don't have time anymore to keep an eye on this project, perhaps you could appoint some collaborers to keep the project alive.

I believe it's awesome and solves a functionality that every other XLSX manipulation library is missing right now.

Currently, I've had to resort to @woodenfish fork to adress the issue of appending merged cells to a table, which is the only showstopper for me to use the main branch. 

It would be neat if that and the other PRs could be merged sometime soon.

**Comment by optilude** [comment]
For some reason I don't seem to be receiving notifications except when @'d :-(

I have limited time for this but @kant2002 picked up a bunch of changed and has npm rights. Maybe he can help?

**Comment by kant2002** [comment]
@amenadiel if you have some PR, could you sent them against my fork?

**Comment by amenadiel** [comment]
@kant2002 so you can create a new tag and publish it to npm? That could become a little confusing for people that will still leave their issues in this repo.

However, the PR I'm talking about is #18 whose author is @woodenfish. I'll ping him to see if he's willing to update his code and make his changes against current HEAD, since his fork was made several months ago and it's now 26 commits behind master.

**Comment by antfu** [comment]
@kant2002 @optilude Would you like to add a few lines to README in this repo mentions about this thing? That will help people to contribute this project. Thanks.

**Comment by kant2002** [comment]
Other option is @optilude give me ability merge to this repro, that could probably solve issue that people going here instead of my fork.

**Comment by optilude** [comment]
Happy to do that. I'm on holiday until mid August but will do it as soon as I can.
		

		Martin Aspeli
	





On Fri, Jul 28, 2017 at 12:25 PM +0100, "Andrey Kurdyumov" <notifications@github.com> wrote:












Other option is @optilude give me ability merge to this repro, that could probably solve issue that people going here instead of my fork.

**Comment by kant2002** [comment]
Enjoy your vacation 🍹

**Comment by optilude** [comment]
Hi,

I think I've invited you to the repo now on GitHub. Let me know when you
manage to accept that.

Martin

**Comment by kant2002** [comment]
I did accept invitation. Will take a look at PRs

**Comment by kant2002** [comment]
I think I made some progress, so this issue could be closed now.
