### ISSUE TITLE
Accessing array elements

### ISSUE THREAD

**Issue by vheuken** [optilude/xlsx-template#55]
It would be nice if I could pass in an array and simply do `${foo[0]}` in the template. Right now, for my use case, I have to do this in my code:

```
const templateData = {
   foo0: foo[0],
   foo1: foo[1],
   ...
}
```

**Comment by kant2002** [comment]
@vheuken Could you try version `xlsx-template@next`

**Comment by vheuken** [comment]
Will try tomorrow. Thanks!

**Comment by vheuken** [comment]
Works as expected. Thanks again. Excellent work you've been doing maintaining this library!
