### ISSUE TITLE
Get same value in diff sheet

### ISSUE THREAD

**Issue by peterhpchen** [optilude/xlsx-template#64]
I have a ${page} which outputs page number for every sheet.
Problem is every sheet ${page} would be the same.

In the subsititueScalar, It replace String for sharedStrings.

```js
// Perform substitution of a single value
    Workbook.prototype.substituteScalar = function(cell, string, placeholder, substitution) {
        var self = this;

        if(placeholder.full && typeof(substitution) === "string") {
            self.replaceString(string, substitution);
        }

        ...

    };
```

So it would not substitute again because the string in sharedStrings is already replaced at first time.

When I comment replaceString in function substituteScalar, this problem is fixed.

Any Idea?

Thanks.

**Comment by kant2002** [comment]
Could you share simple XLSX which exhibit problem and simple data which I should pass to the XLSX template?

**Comment by peterhpchen** [comment]
[template1.xlsx](https://github.com/optilude/xlsx-template/files/1484916/template1.xlsx): This is sample template: it has two sheet, both have a ${page}.

It is my sample code below:
```js
'use strict'

let fs = require('fs');
let XlsxTemplate = require('xlsx-template');

// Load an XLSX file into memory
fs.readFile('./templates/template1.xlsx', function (err, data) {

    // Create a template
    var template = new XlsxTemplate(data);

    for (let sheetNumber = 1; sheetNumber <= 2; sheetNumber++) {
        // Set up some placeholder values matching the placeholders in the template
        var values = {
            page: 'page: ' + sheetNumber
        };

        // Perform substitution
        template.substitute(sheetNumber, values);

    }

    // Get binary data
    var data = template.generate();

    fs.writeFile('./result.xlsx', data, 'binary');
});

```
sheetNumber is changed by 'for loop', but both sheet is output 1.
