### ISSUE TITLE
Ability to dynamically add formula into cell

### ISSUE THREAD

**Issue by RobBrennan** [optilude/xlsx-template#7]
Is there a way to specify a formula for a cell explicitly? I have a value of something like this in my data:
  "formula": "=SUM(B12:B26)"

It correctly puts it in the generated spreadsheet as a formula value, but it doesn't actually trigger calculating the value until I go into the cell and hit the enter key.

**Comment by edi9999** [comment]
Have you found a way to do this ?

**Comment by optilude** [comment]
I don't know enough about the Excel format to know how this would work.

**Comment by mrothberg** [comment]
I know this is an old thread, but this should work now. The calculation chain gets rebuilt now and the formulas automatically evaluate instead of having to press enter on each cell.

**Comment by tolgakurt** [comment]
Unfortunately, it does not work.
