### ISSUE TITLE
Add image into template

### ISSUE THREAD

**Issue by nmquaan** [optilude/xlsx-template#89]
Hi @optilude ,
This is a useful package.
I'm very happy to use it, but I want to add an image into the template, so I have to use another package so this does not interest me, so I hope to support more images.
Please help me!
Thanks for the support!

**Comment by papb** [comment]
@nmquaan May I ask which other package you decided to use? Thanks

**Comment by kant2002** [comment]
Closed by #121 if this is not enough, please create new issue.
