### ISSUE TITLE
Release notes/changelog

### ISSUE THREAD

**Issue by varunnaik** [optilude/xlsx-template#99]
This is more of a tech niggle, but would it be possible to provide release notes or a changelog, as it is unclear if the bump from 0.5.0  ❯  1.0.0 has introduced any breaking changes. Also there is no release for 1.0.0 in this repository though it is present in npmjs.

**Comment by kant2002** [comment]
Thanks for suggestion. I do no longer actively use that package, so my support is more of the validating that existing code works and do not do very big changes. 1.0.0 bump was more indication that I see current API as stable, given how long it was there. But you are right, I should find time and do proper release management.

**Comment by tiholic** [comment]
@kant2002 can you release a new version after the type definitions update?

**Comment by kant2002** [comment]
@tiholic I publish release to NPM and add small release noted in the Release section of GitHub.
